import datetime
from utils.var_helper import SupportedLanguages


def generate_doc(lang):
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    if lang == SupportedLanguages.CSHARP:
        return (
            f"/* This file was automatically generated by SQL2Model\n"
            f"*  It contains a model representation of the SQL table passed\n"
            f"*  Date: {timestamp}\n"
            f"*/\n\n"
        )
    elif lang == SupportedLanguages.PYTHON:
        return (
            f"# This file was automatically generated by SQL2Model\n"
            f"# It contains a model representation of the SQL table passed\n"
            f"# Date: {timestamp}\n\n"
        )
